AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-challenge

  Sample SAM Template for cloud-resume-challenge

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  DomainName:
    Type: String
    Default: "devodriqroberts.com"
  APIDomainName:
    Type: String
    Default: "api."
  DynamoDBTableName:
    Type: String
    Default: "cloud-resume-challenge"
  HostedZoneID:
    Type: String
    Default: "Z05098842II2E0776MPUB"

Resources:
  CloudResumeChallengeWebsite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloud-resume-challenge-2023
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  CloudResumeChallengeRoute53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref "HostedZoneID"
      RecordSets:
        - Name: !Ref "DomainName"
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudResumeChallengeDistribution.DomainName

  CloudResumeChallengeCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join ["", ["*.", !Ref "DomainName"]]
      SubjectAlternativeNames:
        - !Ref "DomainName"
        - !Join ["", ["*.", !Ref "DomainName"]]
      DomainValidationOptions:
        - DomainName: !Ref "DomainName"
          HostedZoneId: !Ref "HostedZoneID"
      ValidationMethod: DNS

  CloudResumeChallengeDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudResumeChallengeCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - !Ref "DomainName"
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: cloud-resume-challenge-2023.s3-website-us-east-1.amazonaws.com
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
            QueryString: false
        Origins:
          - DomainName: cloud-resume-challenge-2023.s3-website-us-east-1.amazonaws.com
            Id: cloud-resume-challenge-2023.s3-website-us-east-1.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: "true"
        DefaultRootObject: index.html
        HttpVersion: http2and3

  ProductBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudResumeChallengeWebsite
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub arn:aws:s3:::${CloudResumeChallengeWebsite}/*

  CloudResumeChallengeSiteVisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/site_visitors.lambda_handler
      Runtime: python3.9
      Description: "Backend for getting and updating site visitors count"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref "DynamoDBTableName"
      Architectures:
        - x86_64
      Events:
        ResumeVisitors:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeViewCountApi
            Path: /site-visitors
            Method: GET

  ResumeViewCountApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        DomainName: !Join ["", [!Ref "APIDomainName", !Ref "DomainName"]]
        CertificateArn: !Ref CloudResumeChallengeCertificate
        Route53:
          HostedZoneId: !Ref "HostedZoneID"
      Cors:
        AllowMethods: "'PUT', 'GET'"
        AllowOrigin: "'devodriqroberts.com'"
      EndpointConfiguration:
        Type: EDGE
      OpenApiVersion: 3.0.1

  CloudResumeChallengeDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-resume-challenge
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"
